project_name: kr8
version: 2
before:
  hooks:
  - go mod download
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    main: .
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: kr8
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
    - LICENSE*
    - README*
    - CHANGELOG*
    - scripts/*
    - docs/*
snapshot:
  version_template: SNAPSHOT-{{ .Commit }}
dist: dist
dockers:
  -
    image_templates: 
      - 'ghcr.io/ice-bergtech/kr8:{{ .Tag }}'
      - 'ghcr.io/ice-bergtech/kr8:latest'
    dockerfile: docker/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
nfpms:
  -
    vendor: 'Iceberg Tech'
    homepage: "https://github.com/ice-bergtech/kr8"
    maintainer: 'Iceberg Tech LLC'
    description: "Opinionated configuration management tool for Kubernetes Cluster"
    license: MIT
    formats:
      - rpm
      - deb
    bindir: /usr/local/bin
brews:
  # https://goreleaser.com/customization/homebrew/
  - name: kr8
    url_template: "https://github.com/ice-bergtech/kr8/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_headers:
    - "Accept: application/octet-stream"
    - 'Authorization: bearer #{ENV["HOMEBREW_TAP_GITHUB_TOKEN"]}'
    download_strategy: CurlDownloadStrategy
    repository:
      owner: ice-bergtech
      name: homebrew-icetech
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
      git:
        url: 'git@github.com:ice-bergtech/homebrew-icetech.git'
        private_key: '{{ .Env.PRIVATE_KEY_PATH }}'

    commit_author:
      name: release
      email: release@icebergtech.xyz
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://ice-bergtech.github.io/kr8"
    description: "Opinionated configuration management tool for Kubernetes Cluster"
    license: MIT
    install: |
      bin.install "kr8"
      bin.install "scripts/kr8-helpers"
    dependencies:
      - helm
      - jsonnet
