# https://www.mkdocs.org/user-guide/configuration/
site_name: kr8+ Docs
site_description: "Documentation for the kr8+ config management tool"
site_author: Iceberg Tech
theme:
  name: readthedocs
  locale: en
  color_mode: dark
  user_color_mode_toggle: true

repo_url: https://github.com/ice-bergtech/kr8/
site_dir: ./_site
docs_dir: ./docs
edit_uri: blob/main/docs
exclude_docs: |
  *.go

nav:
  - Home: index.md
  - Repo Readme: README-repo.md
  - Installation: installation.md
  - Examples 🔗: https://github.com/ice-bergtech/kr8-examples
  - Concepts:
    - Overview: concepts/overview.md
    - Clusters: concepts/clusters.md
    - Components: concepts/components.md
    - Native Funcs: concepts/nativefuncs.md
    - kr8+ Generate Caching: concepts/cache.md
  - Json Schemas:
    - Cluster: schemas/kr8-plus-cluster-schema.json
    - Component: schemas/kr8-plus-component-schema.json
  - Cmd Docs:
    - kr8: cmd/kr8.md
    - kr8 version: cmd/kr8_version.md  
    - kr8 generate: cmd/kr8_generate.md
    - kr8 format: cmd/kr8_format.md
    - kr8 get: 
      - kr8 get: cmd/kr8_get.md
      - kr8 get clusters: cmd/kr8_get_clusters.md
      - kr8 get components: cmd/kr8_get_components.md
      - kr8 get params: cmd/kr8_get_params.md
    - kr8 init:
      - kr8 init: cmd/kr8_init.md
      - kr8 init cluster: cmd/kr8_init_cluster.md
      - kr8 init component: cmd/kr8_init_component.md
      - kr8 init repo: cmd/kr8_init_repo.md
    - kr8 jsonnet: 
      - kr8 jsonnet: cmd/kr8_jsonnet.md
      - kr8 jsonnet render: cmd/kr8_jsonnet_render.md
    - kr8 render:
      - kr8 render: cmd/kr8_render.md
      - kr8 render helm: cmd/kr8_render_helm.md
      - kr8 render jsonnet: cmd/kr8_render_jsonnet.md
  - Godocs:
    - kr8+: godoc/kr8-cmd.md
    - kr8+ types: godoc/kr8-types.md
    - kr8+ generate: godoc/kr8-generate.md
    - kr8+ generate caching: godoc/kr8-cache.md
    - kr8+ Jsonnet Native Functions: godoc/kr8-native-functions.md
    - kr8+ init: godoc/kr8-init.md
    - kr8+ jsonnet: godoc/kr8-jsonnet.md
    - kr8+ util: godoc/kr8-util.md
    - types: godoc/types.md
