version: '3'

tasks:
  default:
    cmds:
      - task: build

  setup:
    desc: 'Instal dev tools'
    cmds:
      # https://golangci-lint.run/welcome/install/
      - brew install golangci-lint
      - brew upgrade golangci-lint
      - git submodule init
      - git submodule update --remote --init

  test:
    desc: Tesk kr8 for your local system
    aliases:
      - t
    cmds:
      - go test
      - golangci-lint run
      - task: build
      - task: test-package

  test-package:
    desc: Test compiled kr8 binary against test inputs
    aliases:
      - tp
    dir: ./bats-test
    env:
      KR8: '../kr8'
    cmds:
      - ./TEST_ALL.sh
  
  setup-tests:
    aliases:
      - st
    dir: ./bats-test
    env:
      KR8: '../kr8'
    cmds:
      - ./GEN_ALL.sh

  build:
    desc: Build kr8 for your local system
    aliases:
      - b
    cmds:
      - go fmt
      - go generate ./docs
      - go build

  build-snapshot:
    desc: Build a snapshot for all platforms using goreleaser
    aliases:
      - bs
    cmds:
      - go generate ./docs
      - goreleaser release --snapshot --clean --skip=homebrew,docker
