version: '3'

tasks:
  default:
    cmds:
      - task: build

  
  test:
    desc: Tesk kr8 for your local system
    aliases:
      - t
    cmds:
      - go test
      - task: build
      - task: test-package

  test-package:
    desc: Test compiled kr8 binary against test inputs
    aliases:
      - tp
    dir: ./bats-test
    env:
      KR8: '../kr8'
    cmds:
      - ./TEST_ALL.sh

  build:
    desc: Build kr8 for your local system
    aliases:
      - b
    cmds:
      - go fmt
      - go generate ./docs
      - go build

  build-snapshot:
    desc: Build a snapshot for all platforms using goreleaser
    aliases:
      - bs
    cmds:
      - go generate ./docs
      - goreleaser release --snapshot --clean --skip=homebrew,docker

  mkdocs:
    desc: Install mkdocs
    cmds:
      - pipenv install mkdocs
      - pipenv install mkdocs-material
  web-local:
    desc: Run the site locally
    cmds:
      - pipenv run mkdocs serve
  web-deploy:
    desc: Build website assets
    cmds:
      - pipenv run mkdocs build
      - pipenv run mkdocs gh-deploy
