version: '2'

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build kr8 for your local system
    cmds:
      - go build

  build-snapshot:
    desc: Build a snapshot for all platforms using goreleaser
    cmds:
      - goreleaser release --snapshot --clean --skip=homebrew,docker

  mkdocs:
    desc: Install mkdocs
    cmds:
      - pipenv install mkdocs
      - pipenv install mkdocs-material
  web-local:
    desc: Run the site locally
    cmds:
      - pipenv run mkdocs serve
  web-deploy:
    desc: Build website assets
    cmds:
      - pipenv run mkdocs build
      - pipenv run mkdocs gh-deploy
