version: '3'

tasks:
  default:
    cmds:
      - task: build

  setup:
    desc: 'Instal dev tools'
    cmds:
      # https://golangci-lint.run/welcome/install/
      - brew install golangci-lint
      - brew upgrade golangci-lint
      - task: setup-bats
  
  setup-bats:
    desc: 'Install bats testing tools'
    cmds:
      - git clone https://github.com/bats-core/bats-core.git bats-test/bats
      - git clone https://github.com/bats-core/bats-support.git bats-test/test_helper/bats-support
      - git clone https://github.com/bats-core/bats-assert.git bats-test/test_helper/bats-assert

  generate-bats-tests:
    aliases:
      - gt
    dir: ./bats-test
    env:
      KR8: '../kr8'
    cmds:
      - ./GEN_ALL.sh

  test:
    desc: Tesk kr8 for your local system
    aliases:
      - t
    cmds:
      - go test
      - golangci-lint run
      - task: build
      - task: test-package

  test-package:
    desc: Test compiled kr8 binary against test inputs
    aliases:
      - tp
    dir: ./bats-test
    env:
      KR8: '../kr8'
    cmds:
      - ./TEST_ALL.sh

  build:
    desc: Build kr8 for your local system
    aliases:
      - b
    cmds:
      - go fmt
      - go generate ./docs
      - go build

  build-snapshot:
    desc: Build a snapshot for all platforms using goreleaser
    aliases:
      - bs
    cmds:
      - go generate ./docs
      - goreleaser release --snapshot --clean --skip=homebrew,docker
