name: CI Tests

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"
  pull_request:
    paths:
      - .github/workflows/test.yml
      - '*.go'
      - 'cmd/*'
      - 'go.mod'
      - 'go.sum'
      - '.goreleaser.yml'
      - 'bats-test/*'
  workflow_dispatch:

jobs:
  test:
    name: CI Testing
    runs-on: ubuntu-latest
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🚧 Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: 🚧 Setup Bats
        uses: bats-core/bats-action@3.0.0
      
      # TODO: add back when there's go tests
      # - name: 🧪 Run go tests
      #   run: go test ./...
      
      # Start of testing steps
      - name: 🧪 Run build
        run: go build
      # Start of bats tests
      - name: 🧪 Run kr8 jsonnet tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats jsonnet_test.sh
      - name: 🧪 Run kr8 render tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats render_test.sh
      - name: 🧪 Run kr8 init tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats init_test.sh
      - name: 🧪 Run kr8 cluster tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats cluster_test.sh
      - name: 🧪 Run kr8 get tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats get_test.sh
      - name: 🧪 Generate Examples and Compare
        run: ./kr8 -B example generate
      - name: Verify no changes were made to tracked files by tests 
        run: git diff --exit-code || echo "Changes detected"

