name: CI Tests

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: CI Testing
    runs-on: ubuntu-latest
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          submodules: true
      - name: 🚧 Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: 🚧 Setup Bats
        uses: bats-core/bats-action@3.0.0
      
      # TODO: add back when there's go tests
      # - name: 🧪 Run go tests
      #   run: go test ./...
      
      # Start of testing steps
      - name: 🧪 Run build
        run: go build
      # Start of bats tests
      - name: 🧪 Run kr8p jsonnet tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats jsonnet_test.sh
      - name: 🧪 Run kr8p render tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats render_test.sh
      - name: 🧪 Run kr8p init tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats init_test.sh
      - name: 🧪 Run kr8p cluster tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats cluster_test.sh
      - name: 🧪 Run kr8p get tests
        env:
          KR8: '../kr8'
        run: cd bats-test && bats get_test.sh
      - name: 🧪 Generate Examples and Compare
        run: ./kr8p -B examples generate
      - name: Verify no changes were made to tracked files by tests 
        run: git diff --exit-code || echo "Changes detected"

